DROP TABLE user_account CASCADE;
DROP TABLE supervisor CASCADE;
DROP TABLE admin CASCADE;
DROP TABLE booking CASCADE;
DROP TABLE bus CASCADE;
DROP TABLE trip CASCADE;
DROP TABLE booking CASCADE;
DROP TABLE cancelled_trip CASCADE;
